general {
    lock_cmd = pidof -x hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 2 && hyprctl dispatch dpms off && sleep 2 && hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

listener {
    timeout = 960
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

