foreground #c5c9c5
background #181616
selection_foreground #b8c8d0
selection_background #2a3a3e
cursor #8ba4b0
cursor_text_color #0d0c0c
url_color #8ea4a2
active_tab_foreground #0d0c0c
active_tab_background #8ba4b0
inactive_tab_foreground #C8C093
inactive_tab_background #282727
color0 #282727
color1 #E82424
color2 #8ba4b0
color3 #8ea4a2
color4 #8992a7
color5 #2a3a3e
color6 #2a3a3a
color7 #c5c9c5
color8 #625e5a
color9 #e8b8b8
color10 #0d0c0c
color11 #0d0c0c
color12 #0d0c0c
color13 #b8c8d0
color14 #b8c8c8
color15 #C8C093
