foreground #c8c09c
background #282825
selection_foreground #b8cce8
selection_background #3a4a6e
cursor #7e9cd8
cursor_text_color #141413
url_color #8ba4b0
active_tab_foreground #141413
active_tab_background #7e9cd8
inactive_tab_foreground #8a8a83
inactive_tab_background #32322e
color0 #32322e
color1 #c4746e
color2 #7e9cd8
color3 #8ba4b0
color4 #8992a7
color5 #3a4a6e
color6 #3a5a5e
color7 #c8c09c
color8 #6c6c66
color9 #e8b8b8
color10 #141413
color11 #141413
color12 #141413
color13 #b8cce8
color14 #b8d0d8
color15 #8a8a83
