font=JetBrainsMono Nerd Font 10
anchor=top-right
background-color=#32322e57
text-color=#c8c09cFF
border-size=1
border-color=#6c6c6638
border-radius=0
width=250
max-visible=3
margin=8
padding=10,14
layer=overlay
markup=0
default-timeout=12000
on-button-left=dismiss
on-button-right=dismiss

[summary~="([Bb]attery.*(full|charged))|((full|charged).*[Bb]attery)|([Cc]harged.*100%)|(100%.*[Cc]harged)"]
invisible=1
