[general]
default-save-path=~/downloads

[viewer]
show-headers=true

[compose]
editor=nvim

[filters]
text/plain = glow
text/html = pandoc -f html -t markdown --wrap=none --reference-links | glow

[ui]
index-format=%D %-17.17n %s
styleset-name=default
