[config]
mode = "dark"
type = "scheme-neutral"
contrast = 0.0

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = ["~/.config/kitty/current-colors.conf"]

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim.jsonc"
output_path = ["~/.cache/matugen/themes/nvim-colors.jsonc"]

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = ["~/.config/rofi/colors.rasi"]

[templates.zed]
input_path = "~/.config/matugen/templates/zed-theme.json"
output_path = ["~/.config/zed/themes/matugen.json"]

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = ["~/.config/waybar/colors.css"]

[templates.obsidian]
input_path = "~/.config/matugen/templates/obsidian.css"
output_path = ["~/Documents/vault/.obsidian/snippets/matugen.css"]

[templates.vesktop]
input_path = "~/.config/matugen/templates/vesktop.css"
output_path = ["~/.config/vesktop/themes/matugen.theme.css"]

[hooks]
post_run = "for SOCK in /tmp/kitty-zizenn-* 2>/dev/null; do [ -S \"$SOCK\" ] && kitty @ --to=\"unix:$SOCK\" set-colors --all --configured ~/.config/kitty/current-colors.conf 2>/dev/null; done"
