hl.on("hyprland.start", function()
	hl.exec_cmd("noctalia --daemon")
	hl.exec_cmd("kitty --single-instance --listen-on unix:/tmp/kitty-zizenn --start-as hidden --detach --session none")
      hl.exec_cmd("vesktop")
      hl.exec_cmd("zen")
end)
