# aerc accounts configuration
# replace with your own account settings.
# see https://aerc-mail.org/ for documentation.

[personal]
source = imaps://user@example.com:993
outgoing = smtps://user@example.com:465
default = INBOX
from = Your Name <user@example.com>
copy-to = Sent
