{ config, pkgs, ... }:

{
  xdg.configFile = {
    "matugen/config.toml".text = ''
      [config]
      mode = "dark"
      type = "scheme-tonal-spot"
      contrast = 0.0

      [templates.kitty]
      input_path = "~/.config/matugen/templates/kitty.conf"
      output_path = ["~/.config/kitty/current-colors.conf"]

      [templates.neovim]
      input_path = "~/.config/matugen/templates/nvim-colors.lua"
      output_path = ["~/.config/nvim/lua/matugen/colors.lua"]

      [templates.quickshell]
      input_path = "~/.config/matugen/templates/quickshell-colors.json"
      output_path = ["~/.config/quickshell/colors.json"]

      [templates.rofi]
      input_path = "~/.config/matugen/templates/rofi-colors.rasi"
      output_path = ["~/.config/rofi/colors.rasi"]

      [templates.zen-chrome]
      input_path = "~/.config/matugen/templates/zen-userChrome.css"
      output_path = ["~/.config/zen/632wsxku.Default Profile/chrome/matugen-chrome.css"]

      [templates.zen-content]
      input_path = "~/.config/matugen/templates/zen-userContent.css"
      output_path = ["~/.config/zen/632wsxku.Default Profile/chrome/matugen-content.css"]

      [templates.pywalfox]
      input_path = "~/.config/matugen/templates/pywalfox-colors.json"
      output_path = ["~/.cache/wal/colors.json"]

      [hooks]
      post_run = "for SOCK in /tmp/kitty-zizenn-* 2>/dev/null; do [ -S \"$SOCK\" ] && kitty @ --to=\"unix:$SOCK\" set-colors --all --configured ~/.config/kitty/current-colors.conf 2>/dev/null; done; if command -v pywalfox >/dev/null 2>&1; then pywalfox update 2>/dev/null || true; fi"
    '';

    "matugen/templates/nvim-colors.lua".text = ''
      -- auto-generated by matugen
      return {
        surface = "{{colors.surface.default.hex}}",
        on_surface = "{{colors.on_surface.default.hex}}",
        surface_variant = "{{colors.surface_variant.default.hex}}",
        on_surface_variant = "{{colors.on_surface_variant.default.hex}}",
        primary = "{{colors.primary.default.hex}}",
        on_primary = "{{colors.on_primary.default.hex}}",
        primary_container = "{{colors.primary_container.default.hex}}",
        on_primary_container = "{{colors.on_primary_container.default.hex}}",
        secondary = "{{colors.secondary.default.hex}}",
        on_secondary = "{{colors.on_secondary.default.hex}}",
        secondary_container = "{{colors.secondary_container.default.hex}}",
        on_secondary_container = "{{colors.on_secondary_container.default.hex}}",
        tertiary = "{{colors.tertiary.default.hex}}",
        on_tertiary = "{{colors.on_tertiary.default.hex}}",
        tertiary_container = "{{colors.tertiary_container.default.hex}}",
        on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}",
        error = "{{colors.error.default.hex}}",
        on_error = "{{colors.on_error.default.hex}}",
        error_container = "{{colors.error_container.default.hex}}",
        on_error_container = "{{colors.on_error_container.default.hex}}",
        outline = "{{colors.outline.default.hex}}",
        background = "{{colors.background.default.hex}}",
        on_background = "{{colors.on_background.default.hex}}",
      }
    '';

    "matugen/templates/quickshell-colors.json".text = ''
      {
        "surface": "{{colors.surface.default.hex}}",
        "cOnSurface": "{{colors.on_surface.default.hex}}",
        "surfaceDim": "{{colors.surface_dim.default.hex}}",
        "surfaceBright": "{{colors.surface_bright.default.hex}}",
        "surfaceContainer": "{{colors.surface_container.default.hex}}",
        "surfaceVariant": "{{colors.surface_variant.default.hex}}",
        "cOnSurfaceVariant": "{{colors.on_surface_variant.default.hex}}",
        "primary": "{{colors.primary.default.hex}}",
        "cOnPrimary": "{{colors.on_primary.default.hex}}",
        "primaryContainer": "{{colors.primary_container.default.hex}}",
        "cOnPrimaryContainer": "{{colors.on_primary_container.default.hex}}",
        "secondary": "{{colors.secondary.default.hex}}",
        "cOnSecondary": "{{colors.on_secondary.default.hex}}",
        "secondaryContainer": "{{colors.secondary_container.default.hex}}",
        "cOnSecondaryContainer": "{{colors.on_secondary_container.default.hex}}",
        "tertiary": "{{colors.tertiary.default.hex}}",
        "cOnTertiary": "{{colors.on_tertiary.default.hex}}",
        "error": "{{colors.error.default.hex}}",
        "cOnError": "{{colors.on_error.default.hex}}",
        "errorContainer": "{{colors.error_container.default.hex}}",
        "cOnErrorContainer": "{{colors.on_error_container.default.hex}}",
        "outline": "{{colors.outline.default.hex}}",
        "outlineVariant": "{{colors.outline_variant.default.hex}}",
        "background": "{{colors.background.default.hex}}",
        "cOnBackground": "{{colors.on_background.default.hex}}"
      }
    '';

    "matugen/templates/rofi-colors.rasi".text = ''
      * {
          background:                     {{colors.surface.default.hex}};
          background-dim:                 {{colors.surface.default.hex}}D9;
          foreground:                     {{colors.on_surface.default.hex}};
          selected-normal-background:     {{colors.primary_container.default.hex}};
          selected-normal-foreground:     {{colors.on_primary_container.default.hex}};
          selected-active-background:     {{colors.secondary_container.default.hex}};
          selected-active-foreground:     {{colors.on_secondary_container.default.hex}};
          selected-urgent-background:     {{colors.error_container.default.hex}};
          selected-urgent-foreground:     {{colors.on_error_container.default.hex}};
          active-background:              {{colors.primary.default.hex}};
          active-foreground:              {{colors.on_primary.default.hex}};
          urgent-background:              {{colors.error.default.hex}};
          urgent-foreground:              {{colors.on_error.default.hex}};
      }
    '';

    "matugen/templates/zen-userChrome.css".text = ''
      /* Auto-generated by matugen - Zen Browser chrome theme */
      :root {
        --matugen-bg: {{colors.background.default.hex}};
        --matugen-bg-dim: {{colors.surface_dim.default.hex}};
        --matugen-surface: {{colors.surface.default.hex}};
        --matugen-surface-bright: {{colors.surface_bright.default.hex}};
        --matugen-surface-container: {{colors.surface_container.default.hex}};
        --matugen-surface-container-low: {{colors.surface_container_low.default.hex}};
        --matugen-surface-container-high: {{colors.surface_container_high.default.hex}};
        --matugen-on-surface: {{colors.on_surface.default.hex}};
        --matugen-on-surface-variant: {{colors.on_surface_variant.default.hex}};
        --matugen-primary: {{colors.primary.default.hex}};
        --matugen-on-primary: {{colors.on_primary.default.hex}};
        --matugen-primary-container: {{colors.primary_container.default.hex}};
        --matugen-on-primary-container: {{colors.on_primary_container.default.hex}};
        --matugen-secondary: {{colors.secondary.default.hex}};
        --matugen-on-secondary: {{colors.on_secondary.default.hex}};
        --matugen-tertiary: {{colors.tertiary.default.hex}};
        --matugen-outline: {{colors.outline.default.hex}};
        --matugen-error: {{colors.error.default.hex}};
      }

      :root {
        --zen-primary-color: var(--matugen-primary);
        --zen-colors-primary: var(--matugen-primary);
        --zen-colors-secondary: var(--matugen-surface-container-high);
        --zen-colors-tertiary: var(--matugen-surface-container);
        --zen-colors-border: var(--matugen-outline);
        --zen-main-browser-background: var(--matugen-bg-dim);
        --zen-themed-toolbar-bg: var(--matugen-bg-dim);
        --zen-themed-toolbar-bg-transparent: var(--matugen-bg-dim);
        --toolbar-bgcolor: var(--matugen-bg-dim);
        --toolbar-color: var(--matugen-on-surface);
        --toolbox-bgcolor-inactive: var(--matugen-bg-dim);
        --lwt-text-color: var(--matugen-on-surface);
        --lwt-accent-color: var(--matugen-primary);
        --lwt-toolbar-field-color: var(--matugen-surface);
        --lwt-toolbar-field-text-color: var(--matugen-on-surface);
        --lwt-toolbar-field-highlight: var(--matugen-primary);
        --lwt-toolbar-field-highlight-text: var(--matugen-on-primary);
        --lwt-sidebar-text-color: var(--matugen-on-surface);
        --lwt-sidebar-background-color: var(--matugen-bg-dim);
        --newtab-background-color: var(--matugen-bg);
        --newtab-text-primary-color: var(--matugen-on-surface);
        --arrowpanel-color: var(--matugen-on-surface);
        --arrowpanel-background: var(--matugen-surface);
        --sidebar-text-color: var(--matugen-on-surface);
        --toolbarbutton-icon-fill: var(--matugen-primary);
      }

      #navigator-toolbox, #titlebar, #TabsToolbar, #tabbrowser-tabs,
      .tabbrowser-tab, .tab-background, .tab-stack,
      #zen-sidebar-splitter, #zen-workspaces-button,
      #zen-appcontent-navbar-container, #urlbar, .urlbar-background,
      menupopup, panel, menu, menuitem,
      .subviewbutton, .toolbarbutton-1 {
        border-radius: 0 !important;
      }

      #zen-main-app-wrapper, #zen-browser-background,
      #navigator-toolbox, #titlebar,
      #tabbrowser-tabs[orient="vertical"], #zen-sidebar-splitter {
        background-color: var(--matugen-bg-dim) !important;
      }

      .tabbrowser-tab[selected] .tab-background,
      .tabbrowser-tab:hover .tab-background {
        background-color: var(--matugen-surface-container-high) !important;
      }
      .tabbrowser-tab:not([selected]):not(:hover) .tab-background {
        background-color: var(--matugen-bg-dim) !important;
      }
      .tabbrowser-tab .tab-label { color: var(--matugen-on-surface) !important; }
      .tabbrowser-tab[selected] .tab-label { color: var(--matugen-primary) !important; }

      #TabsToolbar, #zen-appcontent-navbar-container {
        background-color: var(--matugen-bg-dim) !important;
      }

      .urlbar-background {
        background-color: var(--matugen-surface) !important;
        color: var(--matugen-on-surface) !important;
        border: 1px solid color-mix(in srgb, var(--matugen-primary) 40%, transparent) !important;
      }
      #urlbar[focused="true"] > .urlbar-input-container {
        border-color: var(--matugen-primary) !important;
      }
      .urlbarView-url { color: var(--matugen-primary) !important; }
      #urlbar-results .urlbarView-row[selected] {
        background-color: color-mix(in srgb, var(--matugen-primary) 25%, var(--matugen-surface) 75%) !important;
      }

      .toolbarbutton-1, .urlbar-page-action, #PanelUI-menu-button {
        color: var(--matugen-primary) !important;
        fill: var(--matugen-primary) !important;
      }
      .toolbarbutton-1:hover, .urlbar-page-action:hover, #PanelUI-menu-button:hover {
        background-color: color-mix(in srgb, var(--matugen-primary) 15%, var(--matugen-bg-dim) 85%) !important;
      }

      ::selection, ::-moz-selection {
        background-color: var(--matugen-primary) !important;
        color: var(--matugen-on-primary) !important;
      }

      menupopup, panel { background-color: var(--matugen-surface) !important; color: var(--matugen-on-surface) !important; }
      menupopup menuitem:hover:not([disabled="true"]) {
        background-color: color-mix(in srgb, var(--matugen-primary) 20%, var(--matugen-surface) 80%) !important;
      }

      findbar {
        background-color: var(--matugen-bg-dim) !important;
        border-top: 1px solid var(--matugen-primary) !important;
        --chrome-content-separator-color: var(--matugen-primary) !important;
      }
    '';

    "matugen/templates/zen-userContent.css".text = ''
      /* Auto-generated by matugen - Website content theming */
      :root {
        --matugen-bg: {{colors.background.default.hex}};
        --matugen-bg-dim: {{colors.surface_dim.default.hex}};
        --matugen-surface: {{colors.surface.default.hex}};
        --matugen-surface-container: {{colors.surface_container.default.hex}};
        --matugen-on-surface: {{colors.on_surface.default.hex}};
        --matugen-on-surface-variant: {{colors.on_surface_variant.default.hex}};
        --matugen-primary: {{colors.primary.default.hex}};
        --matugen-on-primary: {{colors.on_primary.default.hex}};
        --matugen-primary-container: {{colors.primary_container.default.hex}};
        --matugen-secondary: {{colors.secondary.default.hex}};
        --matugen-tertiary: {{colors.tertiary.default.hex}};
        --matugen-error: {{colors.error.default.hex}};
        --matugen-outline: {{colors.outline.default.hex}};
      }

      ::selection, ::-moz-selection {
        background-color: var(--matugen-primary) !important;
        color: var(--matugen-on-primary) !important;
      }

      @-moz-document url-prefix("about:") {
        :root {
          --in-content-page-color: var(--matugen-on-surface) !important;
          --in-content-page-background: var(--matugen-bg) !important;
          --color-accent-primary: var(--matugen-primary) !important;
          --link-color: var(--matugen-primary) !important;
        }
      }

      @-moz-document url("about:newtab"), url("about:home") {
        :root {
          --newtab-background-color: var(--matugen-bg) !important;
          --newtab-text-primary-color: var(--matugen-on-surface) !important;
          --newtab-primary-action-background: var(--matugen-primary) !important;
        }
      }

      @-moz-document url-prefix("about:preferences") {
        :root {
          --zen-colors-tertiary: var(--matugen-surface-container-low) !important;
          --zen-primary-color: var(--matugen-primary) !important;
          --in-content-box-background: var(--matugen-surface-container-high) !important;
        }
      }

      @-moz-document url-prefix("http"), url-prefix("https") {
        :root {
          scrollbar-color: var(--matugen-primary) var(--matugen-bg-dim) !important;
          scrollbar-width: thin !important;
        }
        *:focus-visible { outline-color: var(--matugen-primary) !important; }
      }

      @-moz-document domain("google.com"), domain("www.google.com") {
        body, #main, #searchform, .sfbg {
          background-color: var(--matugen-bg) !important;
        }
        a, a:link, a:visited, .yuRUbf a h3, h3.LC20lb {
          color: var(--matugen-primary) !important;
        }
        a:visited, .yuRUbf a:visited h3 {
          color: var(--matugen-secondary) !important;
        }
        input[type="text"], textarea, .gLFyf, .gNO89b, .RNmpXc, .aajZCb {
          background-color: var(--matugen-surface) !important;
          color: var(--matugen-on-surface) !important;
          border-color: var(--matugen-outline) !important;
        }
        .g, .rc, .srg, .r {
          background-color: var(--matugen-surface-container) !important;
        }
        .st, .IsZQTc {
          color: var(--matugen-on-surface-variant) !important;
        }
        #hdtbSum, #hdtbMenus, .hdtb-mitem .hdtb-msel, .hdtb-mitem a {
          background-color: var(--matugen-bg-dim) !important;
          color: var(--matugen-on-surface) !important;
        }
        #nav .nav, #nav a, .navend .n {
          color: var(--matugen-primary) !important;
        }
        #nav .cur {
          color: var(--matugen-on-surface) !important;
          font-weight: bold !important;
        }
        .sfbg, .big, .mw {
          background-color: var(--matugen-bg-dim) !important;
        }
        #gb, .gb_0d, .gb_Od, .gb_2d, .gb_Pd, .gb_g {
          background-color: var(--matugen-bg-dim) !important;
          color: var(--matugen-on-surface) !important;
        }
        .gb_t, .gb_5, .gb_8a, .gb_Ub {
          color: var(--matugen-on-surface) !important;
        }
        circle, .gb_W, .gb_V, .gb_1b {
          fill: var(--matugen-primary) !important;
          color: var(--matugen-primary) !important;
        }
        .fl, .fl a, .fl:visited {
          color: var(--matugen-primary) !important;
        }
        .LC20lb, .DKV0Md {
          color: var(--matugen-on-surface) !important;
        }
        .TbwUpd, .iUh30, .NJjxre {
          color: var(--matugen-on-surface-variant) !important;
        }
      }

      @-moz-document domain("github.com"), domain("gist.github.com") {
        :root {
          --color-canvas-default: var(--matugen-bg) !important;
          --color-page-header-bg: var(--matugen-bg-dim) !important;
          --color-canvas-inset: var(--matugen-bg-dim) !important;
          --color-canvas-subtle: var(--matugen-surface-container) !important;
          --color-sidebar-bg: var(--matugen-bg-dim) !important;
          --color-accent-fg: var(--matugen-primary) !important;
          --color-accent-emphasis: var(--matugen-primary) !important;
          --color-fg-default: var(--matugen-on-surface) !important;
          --color-fg-muted: var(--matugen-on-surface-variant) !important;
          --color-btn-bg: var(--matugen-surface-container) !important;
          --color-btn-border: var(--matugen-outline) !important;
          --color-btn-primary-bg: var(--matugen-primary) !important;
          --color-btn-primary-text: var(--matugen-on-primary) !important;
          --color-input-bg: var(--matugen-surface) !important;
          --color-input-border: var(--matugen-outline) !important;
          --color-success-fg: var(--matugen-tertiary) !important;
          --color-danger-fg: var(--matugen-error) !important;
          --color-border-primary: var(--matugen-outline) !important;
        }
        a { color: var(--matugen-primary) !important; }
      }

      @-moz-document domain("youtube.com") {
        :root {
          --yt-spec-base-background: var(--matugen-bg) !important;
          --yt-spec-raised-background: var(--matugen-bg-dim) !important;
          --yt-spec-menu-background: var(--matugen-surface) !important;
          --yt-spec-surface-background: var(--matugen-surface-container) !important;
          --yt-spec-brand-background-solid: var(--matugen-primary) !important;
          --yt-spec-text-primary: var(--matugen-on-surface) !important;
          --yt-spec-text-secondary: var(--matugen-on-surface-variant) !important;
          --yt-spec-call-to-action: var(--matugen-primary) !important;
          --yt-spec-icon-active-other: var(--matugen-primary) !important;
          --yt-brand-link-text: var(--matugen-primary) !important;
          --yt-searchbox-background: var(--matugen-surface) !important;
          --yt-searchbox-text-color: var(--matugen-on-surface) !important;
          --yt-spec-error-indicator: var(--matugen-error) !important;
        }
        #guide-content.ytd-app { background: var(--matugen-bg-dim) !important; }
        ytd-searchbox { background: var(--matugen-surface) !important; }
        #header.ytd-app { background: var(--matugen-bg-dim) !important; }
      }

      @-moz-document domain("reddit.com") {
        :root {
          --color-neutral-background: var(--matugen-bg) !important;
          --color-neutral-text: var(--matugen-on-surface) !important;
          --color-primary-background: var(--matugen-primary) !important;
          --color-primary-text: var(--matugen-on-primary) !important;
          --color-brand-background: var(--matugen-primary) !important;
          --color-global-text: var(--matugen-on-surface) !important;
          --color-global-background: var(--matugen-bg) !important;
        }
        a { color: var(--matugen-primary) !important; }
        ._2INHSNB6V1WJ_naR2zgsiU { background: var(--matugen-surface) !important; }
        [id|="AppRouter-main"] { background: var(--matugen-bg) !important; }
      }

      @-moz-document domain("news.ycombinator.com") {
        body, table, td { background-color: var(--matugen-bg) !important; color: var(--matugen-on-surface) !important; }
        a:link { color: var(--matugen-primary) !important; }
        a:visited { color: var(--matugen-secondary) !important; }
        .subtext { color: var(--matugen-on-surface-variant) !important; }
        td[bgcolor="#ff6600"] { background: var(--matugen-primary) !important; }
        input[type="text"], textarea {
          background: var(--matugen-surface) !important; color: var(--matugen-on-surface) !important;
          border: 1px solid var(--matugen-outline) !important;
        }
      }

      @-moz-document domain("wikipedia.org") {
        :root {
          --background-color-base: var(--matugen-bg) !important;
          --color-base: var(--matugen-on-surface) !important;
          --color-link: var(--matugen-primary) !important;
          --color-link-visited: var(--matugen-secondary) !important;
          --border-color-base: var(--matugen-outline) !important;
        }
        a { color: var(--matugen-primary) !important; }
        a:visited { color: var(--matugen-secondary) !important; }
      }
    '';

    "matugen/templates/pywalfox-colors.json".text = ''
      {
        "wallpaper": "{{image}}",
        "alpha": "100",
        "colors": {
          "color0":  "{{colors.background.default.hex}}",
          "color1":  "{{colors.error.default.hex}}",
          "color2":  "{{colors.primary.default.hex}}",
          "color3":  "{{colors.tertiary.default.hex}}",
          "color4":  "{{colors.secondary.default.hex}}",
          "color5":  "{{colors.primary_container.default.hex}}",
          "color6":  "{{colors.tertiary_container.default.hex}}",
          "color7":  "{{colors.on_surface.default.hex}}",
          "color8":  "{{colors.outline.default.hex}}",
          "color9":  "{{colors.error_container.default.hex}}",
          "color10": "{{colors.primary.default.hex}}",
          "color11": "{{colors.on_secondary.default.hex}}",
          "color12": "{{colors.secondary_container.default.hex}}",
          "color13": "{{colors.surface_bright.default.hex}}",
          "color14": "{{colors.tertiary_container.default.hex}}",
          "color15": "{{colors.on_surface.default.hex}}"
        }
      }
    '';

    "matugen/templates/kitty.conf".text = ''
      foreground {{colors.on_surface.default.hex}}
      background {{colors.surface.default.hex}}
      selection_foreground {{colors.on_primary_container.default.hex}}
      selection_background {{colors.primary_container.default.hex}}
      cursor {{colors.primary.default.hex}}
      cursor_text_color {{colors.on_primary.default.hex}}
      url_color {{colors.tertiary.default.hex}}
      active_tab_foreground {{colors.on_primary.default.hex}}
      active_tab_background {{colors.primary.default.hex}}
      inactive_tab_foreground {{colors.on_surface_variant.default.hex}}
      inactive_tab_background {{colors.surface_variant.default.hex}}
      color0 {{colors.surface_variant.default.hex}}
      color1 {{colors.error.default.hex}}
      color2 {{colors.primary.default.hex}}
      color3 {{colors.tertiary.default.hex}}
      color4 {{colors.secondary.default.hex}}
      color5 {{colors.primary_container.default.hex}}
      color6 {{colors.tertiary_container.default.hex}}
      color7 {{colors.on_surface.default.hex}}
      color8 {{colors.outline.default.hex}}
      color9 {{colors.on_error_container.default.hex}}
      color10 {{colors.on_primary.default.hex}}
      color11 {{colors.on_tertiary.default.hex}}
      color12 {{colors.on_secondary.default.hex}}
      color13 {{colors.on_primary_container.default.hex}}
      color14 {{colors.on_tertiary_container.default.hex}}
      color15 {{colors.on_surface_variant.default.hex}}
    '';
  };
}
