{ config, pkgs, ... }:

{
  xdg.configFile = {
    "matugen/config.toml".text = ''
      [config]
      mode = "dark"
      type = "scheme-tonal-spot"
      contrast = 0.0

      [templates.kitty]
      input_path = "~/.config/matugen/templates/kitty.conf"
      output_path = ["~/.config/kitty/current-colors.conf"]

      [templates.neovim]
      input_path = "~/.config/matugen/templates/nvim-colors.lua"
      output_path = ["~/.config/nvim/lua/matugen/colors.lua"]

      [templates.quickshell]
      input_path = "~/.config/matugen/templates/quickshell-colors.json"
      output_path = ["~/.config/quickshell/colors.json"]

      [templates.rofi]
      input_path = "~/.config/matugen/templates/rofi-colors.rasi"
      output_path = ["~/.config/rofi/colors.rasi"]

      [templates.zed]
      input_path = "~/.config/matugen/templates/zed-theme.json"
      output_path = ["~/.config/zed/themes/matugen.json"]

      [hooks]
      post_run = "for SOCK in /tmp/kitty-zizenn-* 2>/dev/null; do [ -S \"$SOCK\" ] && kitty @ --to=\"unix:$SOCK\" set-colors --all --configured ~/.config/kitty/current-colors.conf 2>/dev/null; done"
    '';

    "matugen/templates/nvim-colors.lua".text = ''
      -- auto-generated by matugen
      return {
        surface = "{{colors.surface.default.hex}}",
        on_surface = "{{colors.on_surface.default.hex}}",
        surface_variant = "{{colors.surface_variant.default.hex}}",
        on_surface_variant = "{{colors.on_surface_variant.default.hex}}",
        primary = "{{colors.primary.default.hex}}",
        on_primary = "{{colors.on_primary.default.hex}}",
        primary_container = "{{colors.primary_container.default.hex}}",
        on_primary_container = "{{colors.on_primary_container.default.hex}}",
        secondary = "{{colors.secondary.default.hex}}",
        on_secondary = "{{colors.on_secondary.default.hex}}",
        secondary_container = "{{colors.secondary_container.default.hex}}",
        on_secondary_container = "{{colors.on_secondary_container.default.hex}}",
        tertiary = "{{colors.tertiary.default.hex}}",
        on_tertiary = "{{colors.on_tertiary.default.hex}}",
        tertiary_container = "{{colors.tertiary_container.default.hex}}",
        on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}",
        error = "{{colors.error.default.hex}}",
        on_error = "{{colors.on_error.default.hex}}",
        error_container = "{{colors.error_container.default.hex}}",
        on_error_container = "{{colors.on_error_container.default.hex}}",
        outline = "{{colors.outline.default.hex}}",
        background = "{{colors.background.default.hex}}",
        on_background = "{{colors.on_background.default.hex}}",
      }
    '';

    "matugen/templates/quickshell-colors.json".text = ''
      {
        "surface": "{{colors.surface.default.hex}}",
        "cOnSurface": "{{colors.on_surface.default.hex}}",
        "surfaceDim": "{{colors.surface_dim.default.hex}}",
        "surfaceBright": "{{colors.surface_bright.default.hex}}",
        "surfaceContainer": "{{colors.surface_container.default.hex}}",
        "surfaceVariant": "{{colors.surface_variant.default.hex}}",
        "cOnSurfaceVariant": "{{colors.on_surface_variant.default.hex}}",
        "primary": "{{colors.primary.default.hex}}",
        "cOnPrimary": "{{colors.on_primary.default.hex}}",
        "primaryContainer": "{{colors.primary_container.default.hex}}",
        "cOnPrimaryContainer": "{{colors.on_primary_container.default.hex}}",
        "secondary": "{{colors.secondary.default.hex}}",
        "cOnSecondary": "{{colors.on_secondary.default.hex}}",
        "secondaryContainer": "{{colors.secondary_container.default.hex}}",
        "cOnSecondaryContainer": "{{colors.on_secondary_container.default.hex}}",
        "tertiary": "{{colors.tertiary.default.hex}}",
        "cOnTertiary": "{{colors.on_tertiary.default.hex}}",
        "error": "{{colors.error.default.hex}}",
        "cOnError": "{{colors.on_error.default.hex}}",
        "errorContainer": "{{colors.error_container.default.hex}}",
        "cOnErrorContainer": "{{colors.on_error_container.default.hex}}",
        "outline": "{{colors.outline.default.hex}}",
        "outlineVariant": "{{colors.outline_variant.default.hex}}",
        "background": "{{colors.background.default.hex}}",
        "cOnBackground": "{{colors.on_background.default.hex}}"
      }
    '';

    "matugen/templates/rofi-colors.rasi".text = ''
      * {
          background:                     {{colors.surface.default.hex}};
          background-dim:                 {{colors.surface.default.hex}}D9;
          foreground:                     {{colors.on_surface.default.hex}};
          selected-normal-background:     {{colors.primary_container.default.hex}};
          selected-normal-foreground:     {{colors.on_primary_container.default.hex}};
          selected-active-background:     {{colors.secondary_container.default.hex}};
          selected-active-foreground:     {{colors.on_secondary_container.default.hex}};
          selected-urgent-background:     {{colors.error_container.default.hex}};
          selected-urgent-foreground:     {{colors.on_error_container.default.hex}};
          active-background:              {{colors.primary.default.hex}};
          active-foreground:              {{colors.on_primary.default.hex}};
          urgent-background:              {{colors.error.default.hex}};
          urgent-foreground:              {{colors.on_error.default.hex}};
      }
    '';

    "matugen/templates/zed-theme.json".text = ''
      {
        "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
        "name": "Matugen",
        "author": "Generated by Matugen from wallpaper",
        "themes": [
          {
            "name": "Matugen Dark",
            "appearance": "dark",
            "style": {
              "background": "{{colors.background.default.hex}}ff",
              "border": "{{colors.outline.default.hex}}ff",
              "border.variant": "{{colors.outline_variant.default.hex}}ff",
              "border.focused": "{{colors.primary.default.hex}}ff",
              "border.selected": "{{colors.primary_container.default.hex}}ff",
              "border.transparent": "#00000000",
              "border.disabled": "{{colors.surface_variant.default.hex}}ff",
              "elevated_surface.background": "{{colors.surface_container.default.hex}}ff",
              "surface.background": "{{colors.surface_dim.default.hex}}ff",
              "element.background": "{{colors.surface.default.hex}}ff",
              "element.hover": "{{colors.surface_container.default.hex}}ff",
              "element.active": "{{colors.surface_variant.default.hex}}ff",
              "element.selected": "{{colors.primary_container.default.hex}}ff",
              "element.disabled": "{{colors.surface_dim.default.hex}}ff",
              "drop_target.background": "{{colors.primary.default.hex}}80",
              "ghost_element.background": "#00000000",
              "ghost_element.hover": "{{colors.surface_container.default.hex}}ff",
              "ghost_element.active": "{{colors.surface_variant.default.hex}}ff",
              "ghost_element.selected": "{{colors.primary_container.default.hex}}ff",
              "ghost_element.disabled": "{{colors.surface_dim.default.hex}}ff",
              "text": "{{colors.on_surface.default.hex}}ff",
              "text.muted": "{{colors.on_surface_variant.default.hex}}ff",
              "text.placeholder": "{{colors.outline.default.hex}}ff",
              "text.disabled": "{{colors.outline.default.hex}}ff",
              "text.accent": "{{colors.primary.default.hex}}ff",
              "icon": "{{colors.on_surface.default.hex}}ff",
              "icon.muted": "{{colors.on_surface_variant.default.hex}}ff",
              "icon.placeholder": "{{colors.outline.default.hex}}ff",
              "icon.disabled": "{{colors.outline.default.hex}}ff",
              "icon.accent": "{{colors.primary.default.hex}}ff",
              "status_bar.background": "{{colors.surface_dim.default.hex}}ff",
              "title_bar.background": "{{colors.surface_dim.default.hex}}ff",
              "title_bar.inactive_background": "{{colors.background.default.hex}}ff",
              "toolbar.background": "{{colors.surface.default.hex}}ff",
              "tab_bar.background": "{{colors.surface_dim.default.hex}}ff",
              "tab.inactive_background": "{{colors.surface_dim.default.hex}}ff",
              "tab.active_background": "{{colors.surface.default.hex}}ff",
              "search.match_background": "{{colors.primary_container.default.hex}}66",
              "search.active_match_background": "{{colors.tertiary_container.default.hex}}66",
              "panel.background": "{{colors.surface_dim.default.hex}}ff",
              "panel.focused_border": "{{colors.primary.default.hex}}ff",
              "pane.focused_border": "{{colors.primary.default.hex}}ff",
              "scrollbar.thumb.background": "{{colors.on_surface_variant.default.hex}}4c",
              "scrollbar.thumb.hover_background": "{{colors.primary.default.hex}}66",
              "scrollbar.thumb.border": "{{colors.surface_variant.default.hex}}ff",
              "scrollbar.track.background": "#00000000",
              "scrollbar.track.border": "{{colors.surface_variant.default.hex}}ff",
              "editor.foreground": "{{colors.on_surface.default.hex}}ff",
              "editor.background": "{{colors.background.default.hex}}ff",
              "editor.gutter.background": "{{colors.background.default.hex}}ff",
              "editor.subheader.background": "{{colors.surface_dim.default.hex}}ff",
              "editor.active_line.background": "{{colors.primary.default.hex}}1a",
              "editor.highlighted_line.background": "{{colors.primary.default.hex}}0d",
              "editor.line_number": "{{colors.on_surface_variant.default.hex}}80",
              "editor.active_line_number": "{{colors.primary.default.hex}}ff",
              "editor.hover_line_number": "{{colors.on_surface.default.hex}}ff",
              "editor.invisible": "{{colors.surface_variant.default.hex}}ff",
              "editor.wrap_guide": "{{colors.outline_variant.default.hex}}40",
              "editor.active_wrap_guide": "{{colors.outline.default.hex}}80",
              "editor.document_highlight.read_background": "{{colors.primary.default.hex}}1a",
              "editor.document_highlight.write_background": "{{colors.primary_container.default.hex}}66",
              "terminal.background": "{{colors.background.default.hex}}ff",
              "terminal.foreground": "{{colors.on_surface.default.hex}}ff",
              "terminal.bright_foreground": "{{colors.on_surface.default.hex}}ff",
              "terminal.dim_foreground": "{{colors.on_surface_variant.default.hex}}ff",
              "terminal.ansi.black": "{{colors.surface_variant.default.hex}}ff",
              "terminal.ansi.bright_black": "{{colors.outline.default.hex}}ff",
              "terminal.ansi.dim_black": "{{colors.surface_variant.default.hex}}80",
              "terminal.ansi.red": "{{colors.error.default.hex}}ff",
              "terminal.ansi.bright_red": "{{colors.error.default.hex}}ff",
              "terminal.ansi.dim_red": "{{colors.error_container.default.hex}}ff",
              "terminal.ansi.green": "{{colors.primary.default.hex}}ff",
              "terminal.ansi.bright_green": "{{colors.primary.default.hex}}ff",
              "terminal.ansi.dim_green": "{{colors.primary_container.default.hex}}ff",
              "terminal.ansi.yellow": "{{colors.tertiary.default.hex}}ff",
              "terminal.ansi.bright_yellow": "{{colors.tertiary.default.hex}}ff",
              "terminal.ansi.dim_yellow": "{{colors.tertiary_container.default.hex}}ff",
              "terminal.ansi.blue": "{{colors.secondary.default.hex}}ff",
              "terminal.ansi.bright_blue": "{{colors.secondary.default.hex}}ff",
              "terminal.ansi.dim_blue": "{{colors.secondary_container.default.hex}}ff",
              "terminal.ansi.magenta": "{{colors.primary_container.default.hex}}ff",
              "terminal.ansi.bright_magenta": "{{colors.primary_container.default.hex}}ff",
              "terminal.ansi.dim_magenta": "{{colors.primary.default.hex}}80",
              "terminal.ansi.cyan": "{{colors.tertiary_container.default.hex}}ff",
              "terminal.ansi.bright_cyan": "{{colors.tertiary_container.default.hex}}ff",
              "terminal.ansi.dim_cyan": "{{colors.tertiary.default.hex}}80",
              "terminal.ansi.white": "{{colors.on_surface.default.hex}}ff",
              "terminal.ansi.bright_white": "{{colors.on_surface.default.hex}}ff",
              "terminal.ansi.dim_white": "{{colors.on_surface_variant.default.hex}}ff",
              "link_text.hover": "{{colors.primary.default.hex}}ff",
              "version_control.added": "{{colors.tertiary.default.hex}}ff",
              "version_control.modified": "{{colors.primary.default.hex}}ff",
              "version_control.deleted": "{{colors.error.default.hex}}ff",
              "conflict": "{{colors.error.default.hex}}ff",
              "conflict.background": "{{colors.error_container.default.hex}}1a",
              "conflict.border": "{{colors.error_container.default.hex}}ff",
              "created": "{{colors.tertiary.default.hex}}ff",
              "created.background": "{{colors.tertiary_container.default.hex}}1a",
              "created.border": "{{colors.tertiary_container.default.hex}}ff",
              "deleted": "{{colors.error.default.hex}}ff",
              "deleted.background": "{{colors.error_container.default.hex}}1a",
              "deleted.border": "{{colors.error_container.default.hex}}ff",
              "error": "{{colors.error.default.hex}}ff",
              "error.background": "{{colors.error_container.default.hex}}1a",
              "error.border": "{{colors.error_container.default.hex}}ff",
              "hidden": "{{colors.on_surface_variant.default.hex}}ff",
              "hidden.background": "{{colors.surface_container.default.hex}}1a",
              "hidden.border": "{{colors.outline_variant.default.hex}}ff",
              "hint": "{{colors.primary.default.hex}}ff",
              "hint.background": "{{colors.primary_container.default.hex}}1a",
              "hint.border": "{{colors.primary.default.hex}}ff",
              "ignored": "{{colors.on_surface_variant.default.hex}}ff",
              "ignored.background": "{{colors.surface_container.default.hex}}1a",
              "ignored.border": "{{colors.outline_variant.default.hex}}ff",
              "info": "{{colors.secondary.default.hex}}ff",
              "info.background": "{{colors.secondary_container.default.hex}}1a",
              "info.border": "{{colors.secondary_container.default.hex}}ff",
              "modified": "{{colors.primary.default.hex}}ff",
              "modified.background": "{{colors.primary_container.default.hex}}1a",
              "modified.border": "{{colors.primary_container.default.hex}}ff",
              "predictive": "{{colors.on_surface_variant.default.hex}}ff",
              "predictive.background": "{{colors.surface_container.default.hex}}1a",
              "predictive.border": "{{colors.outline_variant.default.hex}}ff",
              "renamed": "{{colors.secondary.default.hex}}ff",
              "renamed.background": "{{colors.secondary_container.default.hex}}1a",
              "renamed.border": "{{colors.secondary_container.default.hex}}ff",
              "success": "{{colors.tertiary.default.hex}}ff",
              "success.background": "{{colors.tertiary_container.default.hex}}1a",
              "success.border": "{{colors.tertiary_container.default.hex}}ff",
              "unreachable": "{{colors.on_surface_variant.default.hex}}ff",
              "unreachable.background": "{{colors.surface_container.default.hex}}1a",
              "unreachable.border": "{{colors.outline_variant.default.hex}}ff",
              "warning": "{{colors.primary.default.hex}}ff",
              "warning.background": "{{colors.primary_container.default.hex}}1a",
              "warning.border": "{{colors.primary_container.default.hex}}ff",
              "players": [],
              "syntax": {
                "attribute":    { "color": "{{colors.secondary.default.hex}}ff", "font_style": null, "font_weight": null },
                "boolean":      { "color": "{{colors.tertiary.default.hex}}ff", "font_style": null, "font_weight": null },
                "comment":      { "color": "{{colors.on_surface_variant.default.hex}}ff", "font_style": "italic", "font_weight": null },
                "comment.doc":  { "color": "{{colors.on_surface_variant.default.hex}}cc", "font_style": "italic", "font_weight": null },
                "constant":     { "color": "{{colors.tertiary.default.hex}}ff", "font_style": null, "font_weight": null },
                "constructor":  { "color": "{{colors.secondary.default.hex}}ff", "font_style": null, "font_weight": null },
                "embedded":     { "color": "{{colors.on_surface.default.hex}}ff", "font_style": null, "font_weight": null },
                "emphasis":     { "color": "{{colors.on_surface.default.hex}}ff", "font_style": "italic", "font_weight": null },
                "emphasis.strong": { "color": "{{colors.on_surface.default.hex}}ff", "font_style": null, "font_weight": 700 },
                "enum":         { "color": "{{colors.tertiary.default.hex}}ff", "font_style": null, "font_weight": null },
                "function":     { "color": "{{colors.primary.default.hex}}ff", "font_style": null, "font_weight": null },
                "hint":         { "color": "{{colors.on_surface_variant.default.hex}}ff", "font_style": "italic", "font_weight": null },
                "keyword":      { "color": "{{colors.primary.default.hex}}ff", "font_style": null, "font_weight": null },
                "label":        { "color": "{{colors.on_surface.default.hex}}ff", "font_style": null, "font_weight": null },
                "link_text":    { "color": "{{colors.primary.default.hex}}ff", "font_style": "underline", "font_weight": null },
                "link_uri":     { "color": "{{colors.tertiary.default.hex}}ff", "font_style": "underline", "font_weight": null },
                "number":       { "color": "{{colors.tertiary.default.hex}}ff", "font_style": null, "font_weight": null },
                "operator":     { "color": "{{colors.on_surface.default.hex}}ff", "font_style": null, "font_weight": null },
                "predictive":   { "color": "{{colors.on_surface_variant.default.hex}}ff", "font_style": "italic", "font_weight": null },
                "preproc":      { "color": "{{colors.primary.default.hex}}cc", "font_style": null, "font_weight": null },
                "primary":      { "color": "{{colors.on_surface.default.hex}}ff", "font_style": null, "font_weight": null },
                "property":     { "color": "{{colors.error.default.hex}}ff", "font_style": null, "font_weight": null },
                "punctuation":  { "color": "{{colors.on_surface.default.hex}}ff", "font_style": null, "font_weight": null },
                "punctuation.bracket": { "color": "{{colors.on_surface.default.hex}}cc", "font_style": null, "font_weight": null },
                "punctuation.delimiter": { "color": "{{colors.on_surface.default.hex}}cc", "font_style": null, "font_weight": null },
                "punctuation.special": { "color": "{{colors.primary.default.hex}}ff", "font_style": null, "font_weight": null },
                "string":       { "color": "{{colors.tertiary.default.hex}}ff", "font_style": null, "font_weight": null },
                "string.escape": { "color": "{{colors.secondary.default.hex}}ff", "font_style": null, "font_weight": null },
                "string.regex": { "color": "{{colors.secondary.default.hex}}ff", "font_style": null, "font_weight": null },
                "string.special": { "color": "{{colors.tertiary.default.hex}}cc", "font_style": null, "font_weight": null },
                "tag":          { "color": "{{colors.primary.default.hex}}ff", "font_style": null, "font_weight": null },
                "text.literal": { "color": "{{colors.tertiary.default.hex}}ff", "font_style": null, "font_weight": null },
                "title":        { "color": "{{colors.primary.default.hex}}ff", "font_style": null, "font_weight": 700 },
                "type":         { "color": "{{colors.secondary.default.hex}}ff", "font_style": null, "font_weight": null },
                "variable":     { "color": "{{colors.on_surface.default.hex}}ff", "font_style": null, "font_weight": null },
                "variable.special": { "color": "{{colors.tertiary.default.hex}}ff", "font_style": null, "font_weight": null },
                "variant":      { "color": "{{colors.on_surface_variant.default.hex}}ff", "font_style": null, "font_weight": null }
              }
            }
          }
        ]
      }
    '';

    "matugen/templates/kitty.conf".text = ''
      foreground {{colors.on_surface.default.hex}}
      background {{colors.surface.default.hex}}
      selection_foreground {{colors.on_primary_container.default.hex}}
      selection_background {{colors.primary_container.default.hex}}
      cursor {{colors.primary.default.hex}}
      cursor_text_color {{colors.on_primary.default.hex}}
      url_color {{colors.tertiary.default.hex}}
      active_tab_foreground {{colors.on_primary.default.hex}}
      active_tab_background {{colors.primary.default.hex}}
      inactive_tab_foreground {{colors.on_surface_variant.default.hex}}
      inactive_tab_background {{colors.surface_variant.default.hex}}
      color0 {{colors.surface_variant.default.hex}}
      color1 {{colors.error.default.hex}}
      color2 {{colors.primary.default.hex}}
      color3 {{colors.tertiary.default.hex}}
      color4 {{colors.secondary.default.hex}}
      color5 {{colors.primary_container.default.hex}}
      color6 {{colors.tertiary_container.default.hex}}
      color7 {{colors.on_surface.default.hex}}
      color8 {{colors.outline.default.hex}}
      color9 {{colors.on_error_container.default.hex}}
      color10 {{colors.on_primary.default.hex}}
      color11 {{colors.on_tertiary.default.hex}}
      color12 {{colors.on_secondary.default.hex}}
      color13 {{colors.on_primary_container.default.hex}}
      color14 {{colors.on_tertiary_container.default.hex}}
      color15 {{colors.on_surface_variant.default.hex}}
    '';
  };
}
