{ config, pkgs, ... }:

{
  xdg.configFile = {
    "nvim/lua/matugen/init.lua".text = ''
      -- matugen colorscheme for neovim
      -- reads colors generated by matugen and applies highlights

      local M = {}
      local colors = {}

      local function load_colors()
        local ok, c = pcall(require, "matugen.colors")
        if ok then
          colors = c
          return true
        end
        return false
      end

      function M.setup(opts)
        opts = opts or {}
        if not load_colors() then
          -- fallback to a minimal dark theme if matugen hasn't run yet
          colors = {
            surface = "#1e1e2e",
            on_surface = "#cdd6f4",
            surface_variant = "#45475a",
            on_surface_variant = "#a6adc8",
            primary = "#89b4fa",
            on_primary = "#1e1e2e",
            primary_container = "#313244",
            on_primary_container = "#89b4fa",
            secondary = "#a6e3a1",
            on_secondary = "#1e1e2e",
            secondary_container = "#313244",
            on_secondary_container = "#a6e3a1",
            tertiary = "#f5c2e7",
            on_tertiary = "#1e1e2e",
            tertiary_container = "#313244",
            on_tertiary_container = "#f5c2e7",
            error = "#f38ba8",
            on_error = "#1e1e2e",
            error_container = "#45475a",
            on_error_container = "#f38ba8",
            outline = "#585b70",
            background = "#11111b",
            on_background = "#cdd6f4",
          }
        end
        M.apply()
      end

      function M.apply()
        local c = colors
        local bg = c.surface
        local fg = c.on_surface

        local function hl(group, opts)
          local cmd = "highlight " .. group
          if opts.fg then cmd = cmd .. " guifg=" .. opts.fg end
          if opts.bg then cmd = cmd .. " guibg=" .. opts.bg end
          if opts.sp then cmd = cmd .. " guisp=" .. opts.sp end
          if opts.style then cmd = cmd .. " gui=" .. opts.style end
          pcall(vim.cmd, cmd)
        end

        -- editor
        hl("Normal", { fg = fg, bg = bg })
        hl("NormalFloat", { fg = fg, bg = c.surface_variant })
        hl("FloatBorder", { fg = c.outline, bg = c.surface_variant })
        hl("CursorLine", { bg = c.surface_variant })
        hl("CursorLineNr", { fg = c.primary })
        hl("CursorColumn", { bg = c.surface_variant })
        hl("LineNr", { fg = c.on_surface_variant })
        hl("SignColumn", { bg = bg })
        hl("ColorColumn", { bg = c.surface_variant })
        hl("Conceal", { fg = c.on_surface_variant })
        hl("Cursor", { fg = bg, bg = fg })
        hl("Visual", { bg = c.primary_container })
        hl("VisualNOS", { bg = c.primary_container })
        hl("Search", { fg = c.on_tertiary_container, bg = c.tertiary_container })
        hl("CurSearch", { fg = c.on_primary, bg = c.primary })
        hl("Substitute", { fg = c.on_error, bg = c.error })
        hl("MatchParen", { fg = c.primary, style = "bold" })
        hl("NonText", { fg = c.outline })
        hl("Whitespace", { fg = c.outline })
        hl("SpecialKey", { fg = c.outline })
        hl("EndOfBuffer", { fg = bg })
        hl("Title", { fg = c.primary, style = "bold" })

        -- split / separator
        hl("WinSeparator", { fg = c.outline })

        -- statusline
        hl("StatusLine", { fg = fg, bg = c.surface_variant })
        hl("StatusLineNC", { fg = c.on_surface_variant, bg = bg })
        hl("TabLine", { fg = c.on_surface_variant, bg = bg })
        hl("TabLineSel", { fg = c.on_primary, bg = c.primary })
        hl("TabLineFill", { bg = bg })

        -- messages / cmdline
        hl("MsgArea", { fg = fg, bg = bg })
        hl("ModeMsg", { fg = c.primary })
        hl("MoreMsg", { fg = c.primary })
        hl("Question", { fg = c.primary })
        hl("WarningMsg", { fg = c.tertiary })
        hl("ErrorMsg", { fg = c.error })

        -- popup menu
        hl("Pmenu", { fg = fg, bg = c.surface_variant })
        hl("PmenuSel", { fg = c.on_primary_container, bg = c.primary_container })
        hl("PmenuKind", { fg = c.tertiary, bg = c.surface_variant })
        hl("PmenuKindSel", { fg = c.on_tertiary_container, bg = c.tertiary_container })
        hl("PmenuExtra", { fg = c.on_surface_variant, bg = c.surface_variant })
        hl("PmenuExtraSel", { fg = c.on_primary_container, bg = c.primary_container })
        hl("PmenuSbar", { bg = c.surface_variant })
        hl("PmenuThumb", { bg = c.outline })

        -- syntax
        hl("Comment", { fg = c.on_surface_variant, style = "italic" })
        hl("String", { fg = c.primary })
        hl("Character", { fg = c.primary })
        hl("Number", { fg = c.primary })
        hl("Boolean", { fg = c.primary })
        hl("Float", { fg = c.primary })
        hl("Function", { fg = c.tertiary })
        hl("Keyword", { fg = c.secondary })
        hl("Statement", { fg = c.secondary })
        hl("Conditional", { fg = c.secondary })
        hl("Repeat", { fg = c.secondary })
        hl("Label", { fg = c.secondary })
        hl("Operator", { fg = fg })
        hl("Exception", { fg = c.error })
        hl("Include", { fg = c.secondary })
        hl("Define", { fg = c.secondary })
        hl("Macro", { fg = c.secondary })
        hl("PreProc", { fg = c.secondary })
        hl("PreCondit", { fg = c.secondary })
        hl("Type", { fg = c.tertiary })
        hl("StorageClass", { fg = c.secondary })
        hl("Structure", { fg = c.tertiary })
        hl("Typedef", { fg = c.tertiary })
        hl("Identifier", { fg = fg })
        hl("Constant", { fg = c.primary })
        hl("Special", { fg = c.primary })
        hl("SpecialChar", { fg = c.primary })
        hl("Tag", { fg = c.tertiary })
        hl("Delimiter", { fg = c.outline })
        hl("SpecialComment", { fg = c.on_surface_variant, style = "italic" })
        hl("Debug", { fg = c.primary })
        hl("Underlined", { fg = c.tertiary, style = "underline" })
        hl("Bold", { style = "bold" })
        hl("Italic", { style = "italic" })
        hl("Ignore", { fg = c.on_surface_variant })
        hl("Todo", { fg = c.on_primary_container, bg = c.primary_container, style = "bold" })

        -- diff
        hl("DiffAdd", { bg = c.primary_container })
        hl("DiffChange", { bg = c.tertiary_container })
        hl("DiffDelete", { bg = c.error_container })
        hl("DiffText", { bg = c.primary_container })

        -- git
        hl("GitSignsAdd", { fg = c.primary })
        hl("GitSignsChange", { fg = c.tertiary })
        hl("GitSignsDelete", { fg = c.error })

        -- diagnostics
        hl("DiagnosticError", { fg = c.error })
        hl("DiagnosticWarn", { fg = c.tertiary })
        hl("DiagnosticInfo", { fg = c.primary })
        hl("DiagnosticHint", { fg = c.secondary })
        hl("DiagnosticOk", { fg = c.primary })
        hl("DiagnosticUnderlineError", { sp = c.error, style = "undercurl" })
        hl("DiagnosticUnderlineWarn", { sp = c.tertiary, style = "undercurl" })
        hl("DiagnosticUnderlineInfo", { sp = c.primary, style = "undercurl" })
        hl("DiagnosticUnderlineHint", { sp = c.secondary, style = "undercurl" })
        hl("DiagnosticUnderlineOk", { sp = c.primary, style = "undercurl" })
        hl("DiagnosticVirtualTextError", { fg = c.error, bg = c.error_container })
        hl("DiagnosticVirtualTextWarn", { fg = c.tertiary, bg = c.tertiary_container })
        hl("DiagnosticVirtualTextInfo", { fg = c.primary, bg = c.primary_container })
        hl("DiagnosticVirtualTextHint", { fg = c.secondary, bg = c.secondary_container })
        hl("DiagnosticFloatingError", { fg = c.error })
        hl("DiagnosticFloatingWarn", { fg = c.tertiary })
        hl("DiagnosticFloatingInfo", { fg = c.primary })
        hl("DiagnosticFloatingHint", { fg = c.secondary })
        hl("DiagnosticSignError", { fg = c.error })
        hl("DiagnosticSignWarn", { fg = c.tertiary })
        hl("DiagnosticSignInfo", { fg = c.primary })
        hl("DiagnosticSignHint", { fg = c.secondary })

        -- telescope
        hl("TelescopeNormal", { fg = fg, bg = bg })
        hl("TelescopeBorder", { fg = c.outline, bg = bg })
        hl("TelescopePromptNormal", { fg = fg, bg = c.surface_variant })
        hl("TelescopePromptBorder", { fg = c.primary, bg = c.surface_variant })
        hl("TelescopePromptTitle", { fg = c.on_primary, bg = c.primary })
        hl("TelescopeResultsTitle", { fg = c.outline, bg = bg })
        hl("TelescopePreviewTitle", { fg = c.outline, bg = bg })
        hl("TelescopeSelection", { bg = c.primary_container })

        -- nvim-tree / neo-tree
        hl("NvimTreeNormal", { fg = fg, bg = bg })
        hl("NvimTreeIndentMarker", { fg = c.outline })
        hl("NvimTreeGitDirty", { fg = c.tertiary })
        hl("NvimTreeGitStaged", { fg = c.primary })
        hl("NvimTreeGitNew", { fg = c.primary })
        hl("NvimTreeRootFolder", { fg = c.primary, style = "bold" })
        hl("NvimTreeOpenedFolderName", { fg = c.tertiary, style = "italic" })
        hl("NvimTreeEmptyFolderName", { fg = c.on_surface_variant })

        -- which-key
        hl("WhichKey", { fg = c.primary })
        hl("WhichKeyGroup", { fg = c.tertiary })
        hl("WhichKeyDesc", { fg = fg })
        hl("WhichKeySeparator", { fg = c.outline })
        hl("WhichKeyBorder", { fg = c.surface_variant })
        hl("WhichKeyFloat", { bg = bg })

        -- lsp
        hl("LspReferenceText", { bg = c.surface_variant })
        hl("LspReferenceRead", { bg = c.surface_variant })
        hl("LspReferenceWrite", { bg = c.surface_variant })
        hl("LspCodeLens", { fg = c.on_surface_variant })
        hl("LspCodeLensSeparator", { fg = c.outline })
        hl("LspSignatureActiveParameter", { fg = c.primary, style = "bold" })
        hl("LspInlayHint", { fg = c.on_surface_variant, bg = c.surface_variant })

        -- treesitter
        hl("@comment", { fg = c.on_surface_variant, style = "italic" })
        hl("@string", { fg = c.primary })
        hl("@string.escape", { fg = c.tertiary })
        hl("@string.regex", { fg = c.tertiary })
        hl("@character", { fg = c.primary })
        hl("@number", { fg = c.primary })
        hl("@boolean", { fg = c.primary })
        hl("@float", { fg = c.primary })
        hl("@function", { fg = c.tertiary })
        hl("@function.builtin", { fg = c.tertiary })
        hl("@function.call", { fg = c.tertiary })
        hl("@function.macro", { fg = c.secondary })
        hl("@parameter", { fg = fg })
        hl("@method", { fg = c.tertiary })
        hl("@field", { fg = c.primary })
        hl("@property", { fg = c.tertiary })
        hl("@constructor", { fg = c.secondary })
        hl("@conditional", { fg = c.secondary })
        hl("@repeat", { fg = c.secondary })
        hl("@keyword", { fg = c.secondary })
        hl("@keyword.function", { fg = c.secondary })
        hl("@keyword.operator", { fg = c.secondary })
        hl("@operator", { fg = fg })
        hl("@exception", { fg = c.error })
        hl("@include", { fg = c.secondary })
        hl("@type", { fg = c.tertiary })
        hl("@type.builtin", { fg = c.tertiary })
        hl("@type.definition", { fg = c.tertiary })
        hl("@type.qualifier", { fg = c.secondary })
        hl("@namespace", { fg = c.tertiary })
        hl("@module", { fg = c.tertiary })
        hl("@label", { fg = c.secondary })
        hl("@constant", { fg = c.primary })
        hl("@constant.builtin", { fg = c.error })
        hl("@constant.macro", { fg = c.secondary })
        hl("@variable", { fg = fg })
        hl("@variable.builtin", { fg = c.error })
        hl("@variable.member", { fg = fg })
        hl("@variable.parameter", { fg = fg })
        hl("@punctuation.delimiter", { fg = c.outline })
        hl("@punctuation.bracket", { fg = c.outline })
        hl("@punctuation.special", { fg = c.primary })
        hl("@tag", { fg = c.tertiary })
        hl("@tag.attribute", { fg = c.primary })
        hl("@tag.delimiter", { fg = c.outline })
        hl("@markup.heading", { fg = c.primary, style = "bold" })
        hl("@markup.italic", { style = "italic" })
        hl("@markup.bold", { style = "bold" })
        hl("@markup.link", { fg = c.tertiary, style = "underline" })
        hl("@markup.link.url", { fg = c.tertiary, style = "underline" })
        hl("@markup.raw", { fg = c.primary })
        hl("@markup.list", { fg = c.tertiary })
        hl("@markup.quote", { fg = c.secondary })
        hl("@diff.plus", { fg = c.primary })
        hl("@diff.minus", { fg = c.error })
        hl("@diff.delta", { fg = c.tertiary })
        hl("@none", {})

        -- notify
        hl("NoiceMsg", { fg = fg })
        hl("NoicePopup", { bg = c.surface_variant })
        hl("NoicePopupmenu", { bg = c.surface_variant })

        vim.g.colors_name = "matugen"
      end

      return M
    '';

    "nvim/lua/plugins/matugen.lua".text = ''
      return {
        dir = vim.fn.stdpath("config") .. "/lua/matugen",
        name = "matugen",
        lazy = false,
        priority = 1000,
        opts = {},
        config = function(_, opts)
          require("matugen").setup(opts)
          vim.schedule(function()
            pcall(vim.cmd.colorscheme, "matugen")
          end)
        end,
      }
    '';
  };
}
