return {
  {
    "nvim-telescope/telescope.nvim",
    cmd = "Telescope",
    version = false,
    dependencies = {
      "nvim-lua/plenary.nvim",
      { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
      "nvim-tree/nvim-web-devicons",
    },
    keys = {
      { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
      { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Live Grep" },
      { "<leader>fb", "<cmd>Telescope buffers<cr>", desc = "Buffers" },
      { "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "Help Tags" },
      { "<leader>fr", "<cmd>Telescope oldfiles<cr>", desc = "Recent Files" },
      { "<leader>fc", "<cmd>Telescope commands<cr>", desc = "Commands" },
      { "<leader>fk", "<cmd>Telescope keymaps<cr>", desc = "Keymaps" },
      { "<leader>fs", "<cmd>Telescope grep_string<cr>", desc = "Grep String" },
      { "<leader>fd", "<cmd>Telescope diagnostics<cr>", desc = "Diagnostics" },
      { "<leader>fm", "<cmd>Telescope marks<cr>", desc = "Marks" },
      { "<leader>f/", "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "Buffer Fuzzy Find" },
      { "<leader>f:", "<cmd>Telescope command_history<cr>", desc = "Command History" },
      { "<leader>f'", "<cmd>Telescope registers<cr>", desc = "Registers" },
      { "<leader>ft", "<cmd>Telescope builtin<cr>", desc = "Telescope Builtin" },
      { "<leader>fw", function() require("telescope.builtin").grep_string({ word_match = "-w" }) end, desc = "Word (root dir)" },
      { "<leader>fW", function() require("telescope.builtin").grep_string({ word_match = "-w", cwd = false }) end, desc = "Word (cwd)" },
      { "<leader>gc", "<cmd>Telescope git_commits<cr>", desc = "Git Commits" },
      { "<leader>gs", "<cmd>Telescope git_status<cr>", desc = "Git Status" },
      { "<leader>gb", "<cmd>Telescope git_branches<cr>", desc = "Git Branches" },
    },
    opts = {
      defaults = {
        prompt_prefix = " ",
        selection_caret = " ",
        entry_prefix = "  ",
        initial_mode = "insert",
        selection_strategy = "reset",
        sorting_strategy = "ascending",
        layout_strategy = "horizontal",
        layout_config = {
          horizontal = { prompt_position = "top", preview_width = 0.55, results_width = 0.8 },
          vertical = { mirror = false },
          width = 0.87,
          height = 0.80,
          preview_cutoff = 120,
        },
        winblend = 0,
        border = "rounded",
        borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
        color_devicons = true,
        set_env = { COLORTERM = "truecolor" },
        file_ignore_patterns = { "%.git/", "node_modules/", "%.cache/", "%.o", "%.a", "%.out", "%.class", "%.pdf", "%.mkv", "%.mp4", "%.zip" },
        path_display = { "truncate" },
        dynamic_preview_title = true,
        mappings = {
          i = {
            ["<C-n>"] = "move_selection_next",
            ["<C-p>"] = "move_selection_previous",
            ["<C-j>"] = "move_selection_next",
            ["<C-k>"] = "move_selection_previous",
            ["<C-c>"] = "close",
            ["<C-u>"] = "preview_scrolling_up",
            ["<C-d>"] = "preview_scrolling_down",
            ["<C-f>"] = "results_scrolling_up",
            ["<C-b>"] = "results_scrolling_down",
          },
          n = { ["q"] = "close", ["<Esc>"] = "close" },
        },
      },
      pickers = {
        find_files = { hidden = true, follow = true },
        live_grep = { additional_args = { "--hidden" } },
        buffers = { sort_lastused = true, ignore_current_buffer = true },
        diagnostics = { theme = "ivy" },
      },
    },
    config = function(_, opts)
      local telescope = require("telescope")
      telescope.setup(opts)
      pcall(telescope.load_extension, "fzf")
    end,
  },
  {
    "nvim-telescope/telescope-fzf-native.nvim",
    build = "make",
    config = function() require("telescope").load_extension("fzf") end,
  },
  {
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    dependencies = { "nvim-lua/plenary.nvim" },
    keys = {
      { "<leader>a", function() require("harpoon"):list():add() end, desc = "Harpoon Add File" },
      { "<C-e>", function() require("harpoon").ui:toggle_quick_menu(require("harpoon"):list()) end, desc = "Harpoon Menu" },
      { "<C-h>", function() require("harpoon"):list():select(1) end, desc = "Harpoon 1" },
      { "<C-j>", function() require("harpoon"):list():select(2) end, desc = "Harpoon 2" },
      { "<C-k>", function() require("harpoon"):list():select(3) end, desc = "Harpoon 3" },
      { "<C-l>", function() require("harpoon"):list():select(4) end, desc = "Harpoon 4" },
      { "<leader>1", function() require("harpoon"):list():select(1) end, desc = "Harpoon 1" },
      { "<leader>2", function() require("harpoon"):list():select(2) end, desc = "Harpoon 2" },
      { "<leader>3", function() require("harpoon"):list():select(3) end, desc = "Harpoon 3" },
      { "<leader>4", function() require("harpoon"):list():select(4) end, desc = "Harpoon 4" },
    },
    config = function() require("harpoon"):setup() end,
  },
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    cmd = "Neotree",
    keys = {
      { "<leader>e", "<cmd>Neotree toggle<cr>", desc = "Explorer" },
      { "<leader>E", "<cmd>Neotree focus<cr>", desc = "Explorer Focus" },
      { "<leader>ge", "<cmd>Neotree float git_status<cr>", desc = "Git Status" },
      { "<leader>be", "<cmd>Neotree float buffers<cr>", desc = "Buffers" },
    },
    deactivate = function() vim.cmd([[Neotree close]]) end,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
    },
    opts = {
      sources = { "filesystem", "buffers", "git_status" },
      open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
      filesystem = {
        bind_to_cwd = false,
        follow_current_file = { enabled = true },
        use_libuv_file_watcher = true,
        filtered_items = { visible = true, hide_dotfiles = false, hide_gitignored = true, hide_by_name = { ".git", "node_modules" } },
      },
      window = {
        mappings = {
          ["<space>"] = "none",
          ["Y"] = "copy_selector",
          ["h"] = "prev_source",
          ["l"] = "next_source",
        },
      },
      default_component_configs = {
        indent = { with_expanders = true, expander_collapsed = "▸", expander_expanded = "▾", expander_highlight = "NeoTreeExpander" },
        icon = { folder_closed = "󰉋", folder_open = "󰝰", folder_empty = "󰉖", default = "󰈙" },
        modified = { symbol = "●" },
        git_status = {
          symbols = { added = "", modified = "", deleted = "✖", renamed = "󰁕", untracked = "", ignored = "", unstaged = "󰄱", staged = "", conflict = "" },
        },
      },
    },
  },
  {
    "folke/flash.nvim",
    event = "VeryLazy",
    keys = {
      { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
      { "S", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
      { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
      { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
      { "<c-s>", mode = "c", function() require("flash").toggle() end, desc = "Toggle Flash Search" },
    },
    opts = {
      labels = "asdfghjklqwertyuiopzxcvbnm",
      search = { multi_window = true, wrap = true, incremental = true },
      jump = { jumplist = true, pos = "start", history = true, register = false, nohlsearch = false, autojump = false },
      label = { uppercase = true, exclude = "", current = true, after = true, before = false, style = "overlay", reuse = "all", distance = true, min_pattern_length = 0 },
      highlight = { backdrop = true, matches = true, groups = { match = "FlashMatch", current = "FlashCurrent", backdrop = "FlashBackdrop", label = "FlashLabel" } },
      modes = {
        search = { enabled = true, highlight = { backdrop = false }, jump = { history = true, register = true, nohlsearch = true } },
        char = { enabled = true, keys = { "f", "F", "t", "T", ";", "," }, highlight = { backdrop = true }, jump = { register = false } },
        treesitter = { labels = "abcdefghijklmnopqrstuvwxyz", jump = { pos = "range" }, highlight = { backdrop = false } },
        remote = { remote_op = { restore = true, motion = true } },
      },
    },
  },
}