color={{colors.background.default.hex}}
image=/home/zizenn/.wallpaper

font=JetBrainsMono Nerd Font
clock
indicator-idle-visible
ignore-empty-password
fade-in=0.2
show-failed-attempts

ring-color={{colors.primary.default.hex}}
ring-ver-color={{colors.secondary.default.hex}}
ring-wrong-color={{colors.error.default.hex}}
ring-caps-lock-color={{colors.tertiary.default.hex}}
inside-color={{colors.surface.default.hex}}99
inside-ver-color={{colors.surface.default.hex}}99
inside-wrong-color={{colors.error_container.default.hex}}99
inside-clear-color={{colors.surface_container.default.hex}}99
inside-caps-lock-color={{colors.surface.default.hex}}99

key-hl-color={{colors.primary.default.hex}}
bs-hl-color={{colors.error.default.hex}}
caps-lock-key-hl-color={{colors.tertiary.default.hex}}
caps-lock-bs-hl-color={{colors.error.default.hex}}

text-color={{colors.on_surface.default.hex}}
text-ver-color={{colors.on_surface.default.hex}}
text-wrong-color={{colors.on_error_container.default.hex}}
text-clear-color={{colors.on_surface.default.hex}}
text-caps-lock-color={{colors.on_surface.default.hex}}

line-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
line-clear-color=00000000
separator-color=00000000

ring-width=4
ring-radius=20