background {
    monitor =
    path = ~/.wallpaper
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8
    brightness = 0.6
    vibrancy = 0.2
    vibrancy_darkness = 0.05
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = #c5c9c5
    font_size = 96
    font_family = JetBrainsMono Nerd Font
    text_align = center
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = #c5c9c5
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    text_align = center
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = #000000
    inner_color = #1D1C19
    font_color = #c5c9c5
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = false
    placeholder_text = Password
    rounding = 0
    check_color = #8ba4b0
    fail_color = #E82424
    fail_text = <b>FAIL</b>
    position = 0, -80
    halign = center
    valign = center
}
