color=#181616
image=/home/zizenn/.wallpaper

font=JetBrainsMono Nerd Font
clock
indicator-idle-visible
ignore-empty-password
fade-in=0.2
show-failed-attempts

ring-color=#8ba4b0
ring-ver-color=#8992a7
ring-wrong-color=#E82424
ring-caps-lock-color=#8ea4a2
inside-color=#18161699
inside-ver-color=#18161699
inside-wrong-color=#3a1a1a99
inside-clear-color=#1D1C1999
inside-caps-lock-color=#18161699

key-hl-color=#8ba4b0
bs-hl-color=#E82424
caps-lock-key-hl-color=#8ea4a2
caps-lock-bs-hl-color=#E82424

text-color=#c5c9c5
text-ver-color=#c5c9c5
text-wrong-color=#e8b8b8
text-clear-color=#c5c9c5
text-caps-lock-color=#c5c9c5

line-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
line-clear-color=00000000
separator-color=00000000

ring-width=4
ring-radius=20