background {
    monitor =
    path = ~/.wallpaper
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8
    brightness = 0.6
    vibrancy = 0.2
    vibrancy_darkness = 0.05
}

label {
    monitor =
    text = cmd[update:1000] date +"<span font_desc='JetBrainsMono Nerd Font 96' foreground='{{colors.on_background.default.hex}}'>%H:%M</span>"
    color = {{colors.on_background.default.hex}}
    font_size = 96
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"<span foreground='{{colors.on_background.default.hex}}' alpha='60%'>%A, %d %B %Y</span>"
    color = {{colors.on_background.default.hex}}
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = #000000
    inner_color = {{colors.surface_container.default.hex}}
    font_color = {{colors.on_surface.default.hex}}
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = true
    placeholder_text =
    rounding = 0
    check_color = {{colors.primary.default.hex}}
    fail_color = {{colors.error.default.hex}}
    fail_text = <b>FAIL</b>
    position = 0, -80
    halign = center
    valign = center
}
