# Where is my SDDM Theme - Matugen generated
font=JetBrainsMono Nerd Font
helpFont=JetBrainsMono Nerd Font
passwordFontSize=36
helpFontSize=14
backgroundFill=#{{colors.surface.default.hex}}
basicTextColor=#{{colors.on_surface.default.hex}}
passwordTextColor=#{{colors.on_surface.default.hex}}
passwordInputBackground=#{{colors.surface_container.default.hex}}
passwordInputRadius=12
passwordCursorColor=#{{colors.primary.default.hex}}
cursorBlinkAnimation=true
hideCursor=false
passwordcharacter=*
passwordMask=true
passwordInputWidth=0.3
